[FlightInfo] 전체 ui 구현
SOPT-33th-JointSeminar-3/Client-Web pull request #38
Opened 2023-11-29 16:26 UTC by ExceptAnyone

## 🔥 Related Issues

resolved #36 

## ✈️ 작업 내용

- [x] 공통 컴포넌트인 Header & FlightLayout & Footer 삽입
- [x] FlightInfomation 컴포넌트
- [x] FlightDate 컴포넌트
- [x] FlightSeat 버튼 컴포넌트
- [x] FlightCard 컴포넌트 구현 후 클릭 시 아래 화면 보이기 & 재사용
- [x] FlightCard 컴포넌트 재사용 시 몇몇 구역엔 "최저가" 삽입

## ✅ PR Point

죄송합니다 여러분!! 작업에 눈이 멀어 ui 구현 후 버튼 클릭 시 기능 + TS까지 같이 작업하고 푸쉬를 해버렸어요....

타입스크립트 진짜 어렵네요.

props에도 타입을 지정해야 한다니...

```typescript
export interface FlightCardProp {
  click: boolean;
  setClick: React.Dispatch<React.SetStateAction<boolean>>;
  handleBtnClick: () => void;
}
```

위 처럼 props로 넘어오는 것들에 대한 타입을 지정하였습니다.

상위 컴포넌트인 FlightCardGroup 에서 버튼의 클릭 시 상태를 저장하기 위해 

```typescript
const FlightCardGroup = () => {
  const [click, setClick] = useState<boolean>(false);

  function handleBtnClick() {
    console.log("클릭!!");
    setClick(!click);
    console.log(!click);
  }
```

이렇게 코드를 구현하였습니다.

그리고 하위 컴포넌트인 FlightCard 에서 

```typescript
<BtnLayout
                className={`${click ? "click" : ""}`}
                onClick={handleBtnClick}
              >
                <CommonTitle className={`${click ? "click" : ""}`}>
                  특가운임
                </CommonTitle>
                <CommonPrice className={`${click ? "click" : ""}`}>
                  48,300원
                </CommonPrice>
                <CommonSeat className={`${click ? "click" : ""}`}>
                  7석
                </CommonSeat>
              </BtnLayout>
```
이렇게 click이 true일 때와 false일 때의 차이로 클래스네임을 변경해서 display: none을 사용하여 유의사항 섹션이 보였다 사라졌다 하는 것을 구현하였습니다.

이렇게 했더니 문제가 있네요.

저는 FlightCard 컴포넌트를 하나 생성 한 후, 이를 상위 컴포넌트에서 전부 재사용하는 형태로 코드를 구현하였는데요.

```typescript
const FlightCardGroup = () => {
  const [click, setClick] = useState<boolean>(false);

  function handleBtnClick() {
    console.log("클릭!!");
    setClick(!click);
    console.log(!click);
  }

  return (
    <>
      <FlightCard
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <FlightCard
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <FlightCard
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <LowestContainer
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <FlightCard
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <LowestContainer
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <FlightCard
        click={click}
        setClick={setClick}
        handleBtnClick={handleBtnClick}
      />
      <FilterIcon>
        <FlightBtnFilter />
      </FilterIcon>
      ;
    </>
  );
};

export default FlightCardGroup;

```

이런식으로 하였더니 하나의 섹션에서 클릭했을 때, 모든 유의사항 섹션이 같이 켜지고 꺼지는 현상이 발생했습니다. 

어떻게 구현해야 버튼 클릭 시 하나의 컴포넌트에서의 섹션만 켜졌다 꺼졌다 구현할 수 있을까요...??

## 😡 Trouble Shooting

position: relative와 absolute를 활용해서 이미지를 겹치는 것의 대한 로직을 배웠습니다.

## 👀 구현 결과물

https://github.com/SOPT-33th-JointSeminar-3/Client-Web/assets/126966681/10d0fd51-a4d1-4b19-94e0-999771dfc154

## 📚 Reference

2023-11-29 18:39 UTC, lydiacho requested changes
고민하고 있는 부분을 PR 포인트에 너무 잘 써줘서 내가 도움 주기도 엄청 수월했어 땡큐땡큐!! 
코드리뷰 잘 읽어보고 문제 해결해보고, 리뷰 이해 안가는 부분있으면 언제든지 질문해 !!

2023-11-29 18:39 UTC, lydiacho commented on korean-air/src/components/flightInfoPage/FlightCardGroup.tsx
> +  }
터치 시에만 보이는 파트 구현하기위해서 useState 활용해준거 접근 아주 잘했어!!

2023-11-29 18:39 UTC, lydiacho commented on korean-air/src/components/flightInfoPage/FlightCardGroup.tsx
> +    </>
PR 확인했고, 
일단 클릭 시 왜 모든 카드의 상태가 다 변하는지 그 문제의 원인은 이해가 됐을까? 
 
그 이유는 오빠는 클릭 시 뜨는 부분의 on/off를 관리하는 state를 'click' 하나를 만들어줬고, 그 하나의 상태값을 모든 카드에서 사용해주고 있기 때문이야! 이해되지? (이부분 이해 안되면 물어봐!) 

그러면 이 여러개의 컴포넌트가 하나의 상태로 on/off로 관리돼서 다 연동이 된거라면, 이 문제를 해결하기 위해선 어떤걸 해야할까? 각 컴포넌트마다 다 다른 on/off state를 만들어서 사용해줘야겠지!

2023-11-29 18:39 UTC, lydiacho commented on korean-air/src/components/flightInfoPage/FlightCardGroup.tsx
> +    </>
근데 그렇다고 해서 그럼 click1, click2, click... 이렇게 state를 생성해버리면 생각만해도 뭔가 지저분한 코드가 되겠지? 
그래서 나라면 여러개의 on/off 상태를 **하나**의 `배열` 상태로 관리할 것 같아! 

예를들어 
`const [click, setClick] = useState([false, false, false, false, ..... ]);` 
이렇게 컴포넌트 갯수만큼의 요소를 가진 배열을 하나의 click 상태로 만들어준 후, 
각 컴포넌트는 자신에게 해당되는 위치(인덱스)의 요소만 접근해서 on/off 값을 업데이트해주고, 반영해주는거지! 

글로 읽어서 이해가 잘 안될텐데 일단 시도해보고, 감이 많이 잘 안잡힌다 싶으면 물어봐!!

2023-11-29 18:39 UTC, lydiacho commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +
props interface 야무지게 만들어준거 처음인데 진짜 잘했다 감동 ,, 타스 적용 아주아주 잘하고 있어

2023-11-29 18:39 UTC, lydiacho commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +              </BtnLayout>
```suggestion
              <BtnLayout
                click={click}
                onClick={handleBtnClick}
              >
                <CommonTitle click={click}>
                  특가운임
                </CommonTitle>
                <CommonPrice click={click}>
                  48,300원
                </CommonPrice>
                <CommonSeat click={click}>
                  7석
                </CommonSeat>
              </BtnLayout>
```

오빠는 지금 click 값에 따라 스타일을 적용해주기 위해서 class를 사용해주고 있는데! 
우리가 3차세미나때 styled components 배우면서 동적 스타일링에 대해 배웠었는데 기억할까?
그때 styled component에게도 props를 넘겨줘서 그 값에 따라 스타일링하는 방법을 배웠었어!! 
[가물가물하면 다시 한번 공부해보자 이건 앞으로도 많이 쓸 내용이기 때문에! ](https://www.notion.so/dosopt/Styled-Components-bccd4244927548cabb4152177fb5134b?pvs=4#94767028b812496ba20985641472d21d)

이렇게 우리는 styled components를 사용해줌으로써 class를 사용하지 않고도 위에 내가 제안한 코드처럼 props를 바로 넘겨줄 수 있어. 받아온 컴포넌트를 어떻게 활용하면 좋을지는 아래부분에서 다시 코멘트 달게!

2023-11-29 18:39 UTC, lydiacho commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +  }
```suggestion
  background: ${ click ? theme.colors.navy : theme.colors.white };
```

그럼 이제 이 부분은 이렇게 바꿔줄 수 있겠지?! 
삼항 연산자가 익숙하지 않을 수 있으니까 설명하자면 저 코드는 click 값이 true면 navy 색으로, false면 white 색으로 지정해줘~ 라는 뜻이야. 

그럼 여기서 끝이 아니고, 
우리는 JS가 아니라 TS를 사용해주고 있기 때문에 아마 이렇게만 적용시켜주면 위에서 props를 내려주는 곳에서 빨간 줄이 뜰거야! 그건 넘겨주는 props에 대한 타입 지정을 해주지 않았기 때문인데, **styled-components에게 넘겨주는 props는 타입지정을 반드시 해줘야하고**, 해주는 방식은 다음과 같아.
```js
const BtnLayout = styled.section<{click : boolean}>`
  // ...
` 
```
이렇게 어떤 element 써줄지 지정해주는 것과 백틱 사이에 대괄호를 넣어주고 그안에 타입을 지정해주는 중괄호를 넣어주면 돼! 

관련된 자료 링크 달아놓을테니까 꼭꼭 읽어보고 잘 써보자 ! 
[블로그 링크 : TS에서 styled components props 쓰기](https://thsd-stjd.tistory.com/134)

2023-11-29 18:40 UTC, lydiacho approved these changes

2023-11-30 01:07 UTC, qwp0 reviewed
최고최고👍🏻👍🏻 여기도 이거 한번만 확인해주세요!!
<img width="374" alt="스크린샷 2023-11-30 오전 10 06 51" src="https://github.com/SOPT-33th-JointSeminar-3/Client-Web/assets/102568726/aeddf050-483e-4739-9016-fd4cdfd6e3dd">

2023-11-30 01:07 UTC, qwp0 commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +
타스 적용 잘한다...나도 더 공부할게...

2023-11-30 01:07 UTC, qwp0 commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +  }
나도 참고 링크 열심히 읽어볼게 ! 짱짱

2023-11-30 01:07 UTC, qwp0 commented on korean-air/src/components/flightInfoPage/FlightCardGroup.tsx
> +    </>
설명 너무 친절해요 😮👍🏻 난 오빠 pr보고 state 다 생성해야하나 생각했는데 배열로 상태 관리하면 진짜 훨씬 깔끔하겠다 !

2023-11-30 01:07 UTC, qwp0 commented on korean-air/src/components/flightInfoPage/LowestContainer.tsx
> +        </div>
안쓰는 코드는 지워도 될 것 같아유

2023-11-30 03:25 UTC, ExceptAnyone commented on korean-air/src/components/flightInfoPage/FlightCardGroup.tsx
> +    </>
오 고마워 고마워 이따 신사역에서 한번더 물어볼게 ㅎㅎ

2023-11-30 03:26 UTC, ExceptAnyone commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +
아니 저거 4줄 치는데 1시간 넘게 걸렸음요 여러분... 구글링 무지하게 함 ㅋㅋㅋㅋㅋㅋ

2023-11-30 03:28 UTC, ExceptAnyone commented on korean-air/src/components/flightInfoPage/FlightCard.tsx
> +              </BtnLayout>
아 링크 보니까 기억났어 ㅋㅋㅋㅋㅋㅋ 이따 적용시키겠습니다

2023-11-30 05:36 UTC, merged